services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
